services:
  db:
    image: postgres:16-alpine
    container_name: asadas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: asadas_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: asadas-redis
    ports:
      - "6379:6379"
EOF
